<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Event;
use App\Attendance;
use Illuminate\Support\Facades\DB;

class MigrateFormsSchema extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'migrate:forms';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Migrate old attendance tags (respostes personalitzades) into FormBuilder JSON schema.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $events = Event::has('attendanceAnswers')->with('attendanceAnswers')->get();

        $this->info("Found " . $events->count() . " events with old attendance tags.");

        $bar = $this->output->createProgressBar(count($events));

        DB::beginTransaction();
        try {
            foreach ($events as $event) {
                // Build checkbox group
                $options = [];
                $tagIdToValue = [];

                foreach ($event->attendanceAnswers as $tag) {
                    $options[] = [
                        'label' => $tag->name,
                        'value' => (string) $tag->id_tag,
                        'selected' => false
                    ];
                    $tagIdToValue[$tag->id_tag] = (string) $tag->id_tag;
                }

                $checkboxName = 'legacy-tags-' . $event->id_event;

                $formSchema = [
                    [
                        "type" => "checkbox-group",
                        "required" => false,
                        "label" => "Respostes",
                        "toggle" => false,
                        "inline" => false,
                        "name" => $checkboxName,
                        "values" => $options
                    ]
                ];

                $event->form_schema = $formSchema;
                $event->save();

                // Now we must migrate the attendances for this event to use the new object structure generated by formbuilder
                // Form builder output will be: {"legacy-tags-123": ["28", "29"]}
                $attendances = Attendance::where('event_id', $event->id_event)->whereNotNull('options')->get();
                foreach ($attendances as $attendance) {
                    $oldOptions = $attendance->options; 
                    if (is_array($oldOptions) && !empty($oldOptions)) {
                        // Check if it's already migrated (has string keys)
                        if (array_keys($oldOptions) !== range(0, count($oldOptions) - 1)) {
                            continue;
                        }
                        
                        $attendance->options = [
                            $checkboxName => array_map('strval', $oldOptions)
                        ];
                        $attendance->save();
                    } elseif (is_string($oldOptions)) {
                        $decoded = json_decode($oldOptions, true);
                        if (is_array($decoded) && !empty($decoded)) {
                             if (array_keys($decoded) !== range(0, count($decoded) - 1)) {
                                continue;
                            }
                            $attendance->options = [
                                $checkboxName => array_map('strval', $decoded)
                            ];
                            $attendance->save();
                        }
                    }
                }

                $bar->advance();
            }

            DB::commit();
            $bar->finish();
            $this->info("\nMigration completed successfully.");
        } catch (\Exception $e) {
            DB::rollBack();
            $this->error("\nError migrating: " . $e->getMessage());
            return 1;
        }

        return 0;
    }
}
