name: Release and Publish Docker Image

on:
  release:
    types: [released]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract the version from the release
      - name: Get version from release
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Setup docker buildx
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      # Step 5: Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/associaciofempinya/backend:${{ env.RELEASE_VERSION }}
            ghcr.io/associaciofempinya/backend:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: build/App.Dockerfile
